WA_Flags = {
	'0': ':flag_gb:',
	'1': ':flag_ar:',
	'2': ':flag_au:',
	'3': ':flag_at:',
	'4': ':flag_be:',
	'5': ':flag_br:',
	'6': ':flag_ca:',
	'7': ':flag_hr:',  # unsure
	'8': ':flag_ba:',
	'9': ':flag_cy:',
	'10': ':flag_cz:',
	'11': ':flag_dk:',
	'12': ':flag_fi:',
	'13': ':flag_fr:',
	'14': ':flag_ge:',
	'15': ':flag_de:',
	'16': ':flag_gr:',
	'17': ':flag_hk:',
	'18': ':flag_hu:',
	'19': ':flag_is:',
	'20': ':flag_in:',
	'21': ':flag_id:',
	'22': ':flag_ir:',
	'23': ':flag_iq:',
	'24': ':flag_ie:',
	'25': ':flag_il:',
	'26': ':flag_it:',
	'27': ':flag_jp:',
	'28': ':flag_li:',
	'29': ':flag_lu:',
	'30': ':flag_my:',
	'31': ':flag_mt:',
	'32': ':flag_mx:',
	'33': ':flag_ma:',
	'34': ':flag_nl:',
	'35': ':flag_nz:',
	'36': ':flag_no:',
	'37': ':flag_pl:',
	'38': ':flag_pt:',
	# '39': ':checkered_flag:', # unsure
	'40': ':flag_ro:',
	'41': ':flag_ru:',
	'42': ':flag_sg:',
	'43': ':flag_za:',
	'44': ':flag_es:',
	'45': ':flag_se:',
	'46': ':flag_ch:',
	'47': ':flag_tr:',
	'48': ':flag_us:',
	# '49': ':checkered_flag:', # unsure
	# '50': ':checkered_flag:', # unsure
	# '51': ':checkered_flag:', # unsure
	# '52': ':checkered_flag:', # unsure
	'53': ':flag_cl:',
	# '54': ':checkered_flag:', # unsure
	'55': ':flag_si:',
	'56': ':flag_lb:',
	# '57': ':checkered_flag:', # unsure
	'58': ':flag_ua:',
	'59': ':flag_lv:',
	'60': ':flag_rs:',
	# '61': ':checkered_flag:', #unsure
	'62': ':flag_ee:',
	'63': ':flag_cn:',
	'64': ':flag_co:',
	'65': ':flag_ec:',
	'66': ':flag_uy:',
	'67': ':flag_ve:',
	# '68': ':flag_mm:', #unsure
	'69': ':flag_bg:',
	'70': ':flag_eg:',
	'71': ':flag_sa:',
	'72': ':flag_kr:',
	'73': ':flag_by:',
	'74': ':flag_pe:',
	'75': ':flag_dz:',
	'76': ':flag_kz:',
	'77': ':flag_ni:',
	'78': ':flag_tw:',
	'79': ':flag_jm:',
	'80': ':flag_gt:',
	'81': ':flag_mh:',
	'82': ':flag_mk:',
	'83': ':flag_ae'
}
